theme:
  switch: true
  default: auto

favicon:
  logo: https://avatars.githubusercontent.com/u/94727944
  icon16: https://avatars.githubusercontent.com/u/94727944?s=16&v=4
  icon32: https://avatars.githubusercontent.com/u/94727944?s=32&v=4
  apple_touch_icon: https://avatars.githubusercontent.com/u/94727944
  webmanifest: /site.webmanifest
  visibilitychange: true
  hidden: failure.ico
  show_text: (/≧▽≦/)咦！又好了！
  hide_text: (〒︿〒)喔哟，崩溃啦！

user:
  name: 小朱
  first_name: zhu
  last_name: xiao
  email: xiaozhuABCD1234@163.com
  domain:
  avatar: https://avatars.githubusercontent.com/u/94727944
  describe: 个人博客
  rule_text: 暂不接受个人博客以外的友链申请。

top_bars:
  - title: 首页
    url: /
  - title: 归档
    url: /archives/
    noswup: true
  - title: 分类
    url: /categories/
  - title: 标签
    url: /tags/
    noswup: true
  - title: 友链
    url: /links/
    noswup: true
  - title: 关于
    url: /about/
    noswup: true

sidebar:
  social: # 社交地址
    - name: github
      icon: fab fa-github
      url: https://github.com/xiaozhuABCD1234
  typed_text_prefix: I`m
  typed_text: ["Developer", "Student"]
  # typed_text: ["大雨落幽燕，白浪滔天，秦皇岛外打鱼船。 一片汪洋都不见，知向谁边？ 往事越千年，魏武挥鞭，东临碣石有遗篇。 萧瑟秋风今又是，换了人间。 "]
  info: # 个人信息
    - key: 地址
      val: 地球

toc:
  enable: true
  list_number: true
  post_title: true
  max_depth: 4
  min_depth: 1

lazyload:
  enable: true

cover:
  default:
    - https://images.pexels.com/photos/1054218/pexels-photo-1054218.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1
    - https://images.pexels.com/photos/16533675/pexels-photo-16533675.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1
    - https://images.pexels.com/photos/9391325/pexels-photo-9391325.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1
  type: random #可选 img || date || random

notice_outdate:
  enable: true
  style: flat
  limit_day: 365
  position: top

banner:
  use_cover: true # Use the cover image for article details | 文章详情使用封面图
  default: # 默认横幅配置
    type: img # 横幅类型 <[img,slideshow,video]>
    bgurl: /img/banner.png # 背景图地址
    banner_text: Hi my new friend! # 横幅描述
    position: top # 同 CSS object-position
    fit: cover # 同 CSS object-fit
  index: ## 首页横幅
    banner_title: 树深时见鹿，<br>溪午不闻钟。
    banner_text: Hi my new friend!
    video_url: # 视频地址
  archive: ## 归档页横幅
    banner_title: 云间连下榻，<br>天上接行杯。
    banner_text: The article archive
  links: ## 友链页横幅
    banner_title: 莫愁前路无知己，<br>天下谁人不识君。
    banner_text: A link to a friend's website
  comment: ## 评论页横幅
    banner_title: 醉后不知天在水，<br>满船清梦压星河。
    banner_text: The magic tree hole
  about: ## 关于页横幅
    banner_title: 君子豹变，<br>其文蔚也。
    banner_text: About me

# about:
#   insert: after # 插入规则 before（插入在内容前） | after（插入在内容后） | none（不插入）
#   title: 在坚冰还盖着北海的时候，我看到了怒放的梅花
#   introduction: 个人简单描述
#   blog: 
#   privacy: 隐私权说明
about:
  insert: none #  插入规则  <[before,after,none]>
  title: 在坚冰还盖着北海的时候，我看到了怒放的梅花 # 标题
  introduction: 大家好，我是 <strong>小朱</strong>，很高兴您能在浩瀚如烟的互联网世界里发现这个博客，更感谢您能够饶有兴致地浏览这个页面。建立这个 Blog 是出于兴趣爱好，我将在此分会分享一些学习笔记，可能还会分享少许图片、视频以及其他有趣东西的链接。 # 个人简单描述
  blog: <ul class="trm-list"><li>程序：Hexo </li><li>主题：Hexo-theme-async </li></ul> <br> <p>内容仅代表个人观点，不构成任何投资 / 决策建议，具体请以实际情况为准。如涉及行业案例，均为公开信息整理，不针对任何特定主体，若有巧合纯属意外。文中数据源自网络或第三方机构，不保证绝对准确性，仅供参考讨论。观点可能随时间变化，后续不作主动更新，建议结合最新信息独立判断。</p> # 博客信息 
  privacy: 本网站不会追踪访客行为，且不要求访客提供任何敏感信息（比如真实姓名、身份证号码、手机号等），因而也不存在任何隐私泄漏问题。访客参与评论，必须遵守法律法规和基本道德规范，文明礼貌。严禁发布任何有关淫秽、反动、暴力、博彩、恐吓、低俗的内容或违法信息，在尊重言论自由的同时请保持和平与理性。请勿对他人采取不友好的评论或其它过激行为。 # 隐私权说明

footer:
  # Hexo link (Powered by Hexo).
  powered: # 程序驱动信息
    enable: true # 启用
  # Beian icp information for Chinese users. In China, every legal website should have a beian icp in website footer.
  # https://beian.miit.gov.cn/
  beian: # 备案信息
    enable: false # 启用
    icp: # 备案号
  # Copyright date
  copyright_year: # 版权日期
  #
  live_time: # 运行时间
    enable: true # 启用
    prefix: footer.tips # 计时文案
    start_time: 12/26/2023 21:00:00 # 计时开始时间
  #
  custom_text: ## 自定义内容